//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace K3CloudCs.ServiceReference1 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://common.api.alibaba.com")]
    public partial class ApiExceptionInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestIdField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("requestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.product.api.alibaba.com")]
    public partial class ProductBizGroupInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<bool> supportField;
        
        private string descriptionField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<bool> support {
            get {
                return this.supportField;
            }
            set {
                this.supportField = value;
                this.RaisePropertyChanged("support");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.product.api.alibaba.com")]
    public partial class ProductExtendInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.product.api.alibaba.com")]
    public partial class ProductInternationalTradeInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fobCurrencyField;
        
        private string fobMinPriceField;
        
        private string fobMaxPriceField;
        
        private string fobUnitTypeField;
        
        private string[] paymentMethodsField;
        
        private System.Nullable<int> minOrderQuantityField;
        
        private string minOrderUnitTypeField;
        
        private System.Nullable<int> supplyQuantityField;
        
        private string supplyUnitTypeField;
        
        private string supplyPeriodTypeField;
        
        private string deliveryPortField;
        
        private string deliveryTimeField;
        
        private System.Nullable<int> consignmentDateField;
        
        private string packagingDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string fobCurrency {
            get {
                return this.fobCurrencyField;
            }
            set {
                this.fobCurrencyField = value;
                this.RaisePropertyChanged("fobCurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string fobMinPrice {
            get {
                return this.fobMinPriceField;
            }
            set {
                this.fobMinPriceField = value;
                this.RaisePropertyChanged("fobMinPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string fobMaxPrice {
            get {
                return this.fobMaxPriceField;
            }
            set {
                this.fobMaxPriceField = value;
                this.RaisePropertyChanged("fobMaxPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string fobUnitType {
            get {
                return this.fobUnitTypeField;
            }
            set {
                this.fobUnitTypeField = value;
                this.RaisePropertyChanged("fobUnitType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayElement")]
        public string[] paymentMethods {
            get {
                return this.paymentMethodsField;
            }
            set {
                this.paymentMethodsField = value;
                this.RaisePropertyChanged("paymentMethods");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> minOrderQuantity {
            get {
                return this.minOrderQuantityField;
            }
            set {
                this.minOrderQuantityField = value;
                this.RaisePropertyChanged("minOrderQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string minOrderUnitType {
            get {
                return this.minOrderUnitTypeField;
            }
            set {
                this.minOrderUnitTypeField = value;
                this.RaisePropertyChanged("minOrderUnitType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> supplyQuantity {
            get {
                return this.supplyQuantityField;
            }
            set {
                this.supplyQuantityField = value;
                this.RaisePropertyChanged("supplyQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string supplyUnitType {
            get {
                return this.supplyUnitTypeField;
            }
            set {
                this.supplyUnitTypeField = value;
                this.RaisePropertyChanged("supplyUnitType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string supplyPeriodType {
            get {
                return this.supplyPeriodTypeField;
            }
            set {
                this.supplyPeriodTypeField = value;
                this.RaisePropertyChanged("supplyPeriodType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string deliveryPort {
            get {
                return this.deliveryPortField;
            }
            set {
                this.deliveryPortField = value;
                this.RaisePropertyChanged("deliveryPort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string deliveryTime {
            get {
                return this.deliveryTimeField;
            }
            set {
                this.deliveryTimeField = value;
                this.RaisePropertyChanged("deliveryTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> consignmentDate {
            get {
                return this.consignmentDateField;
            }
            set {
                this.consignmentDateField = value;
                this.RaisePropertyChanged("consignmentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string packagingDesc {
            get {
                return this.packagingDescField;
            }
            set {
                this.packagingDescField = value;
                this.RaisePropertyChanged("packagingDesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.product.api.alibaba.com")]
    public partial class ProductShippingInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> freightTemplateIDField;
        
        private System.Nullable<double> unitWeightField;
        
        private string packageSizeField;
        
        private System.Nullable<int> volumeField;
        
        private System.Nullable<int> handlingTimeField;
        
        private System.Nullable<long> sendGoodsAddressIdField;
        
        private string sendGoodsAddressTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> freightTemplateID {
            get {
                return this.freightTemplateIDField;
            }
            set {
                this.freightTemplateIDField = value;
                this.RaisePropertyChanged("freightTemplateID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<double> unitWeight {
            get {
                return this.unitWeightField;
            }
            set {
                this.unitWeightField = value;
                this.RaisePropertyChanged("unitWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string packageSize {
            get {
                return this.packageSizeField;
            }
            set {
                this.packageSizeField = value;
                this.RaisePropertyChanged("packageSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
                this.RaisePropertyChanged("volume");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> handlingTime {
            get {
                return this.handlingTimeField;
            }
            set {
                this.handlingTimeField = value;
                this.RaisePropertyChanged("handlingTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<long> sendGoodsAddressId {
            get {
                return this.sendGoodsAddressIdField;
            }
            set {
                this.sendGoodsAddressIdField = value;
                this.RaisePropertyChanged("sendGoodsAddressId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string sendGoodsAddressText {
            get {
                return this.sendGoodsAddressTextField;
            }
            set {
                this.sendGoodsAddressTextField = value;
                this.RaisePropertyChanged("sendGoodsAddressText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.product.api.alibaba.com")]
    public partial class ProductSaleInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<bool> supportOnlineTradeField;
        
        private System.Nullable<bool> mixWholeSaleField;
        
        private string saleTypeField;
        
        private System.Nullable<bool> priceAuthField;
        
        private ProductPriceRange[] priceRangesField;
        
        private System.Nullable<double> amountOnSaleField;
        
        private string unitField;
        
        private System.Nullable<int> minOrderQuantityField;
        
        private System.Nullable<int> batchNumberField;
        
        private System.Nullable<double> retailpriceField;
        
        private string taxField;
        
        private string sellunitField;
        
        private System.Nullable<int> quoteTypeField;
        
        private System.Nullable<double> consignPriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<bool> supportOnlineTrade {
            get {
                return this.supportOnlineTradeField;
            }
            set {
                this.supportOnlineTradeField = value;
                this.RaisePropertyChanged("supportOnlineTrade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<bool> mixWholeSale {
            get {
                return this.mixWholeSaleField;
            }
            set {
                this.mixWholeSaleField = value;
                this.RaisePropertyChanged("mixWholeSale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string saleType {
            get {
                return this.saleTypeField;
            }
            set {
                this.saleTypeField = value;
                this.RaisePropertyChanged("saleType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<bool> priceAuth {
            get {
                return this.priceAuthField;
            }
            set {
                this.priceAuthField = value;
                this.RaisePropertyChanged("priceAuth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayElement")]
        public ProductPriceRange[] priceRanges {
            get {
                return this.priceRangesField;
            }
            set {
                this.priceRangesField = value;
                this.RaisePropertyChanged("priceRanges");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<double> amountOnSale {
            get {
                return this.amountOnSaleField;
            }
            set {
                this.amountOnSaleField = value;
                this.RaisePropertyChanged("amountOnSale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> minOrderQuantity {
            get {
                return this.minOrderQuantityField;
            }
            set {
                this.minOrderQuantityField = value;
                this.RaisePropertyChanged("minOrderQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> batchNumber {
            get {
                return this.batchNumberField;
            }
            set {
                this.batchNumberField = value;
                this.RaisePropertyChanged("batchNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<double> retailprice {
            get {
                return this.retailpriceField;
            }
            set {
                this.retailpriceField = value;
                this.RaisePropertyChanged("retailprice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string tax {
            get {
                return this.taxField;
            }
            set {
                this.taxField = value;
                this.RaisePropertyChanged("tax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string sellunit {
            get {
                return this.sellunitField;
            }
            set {
                this.sellunitField = value;
                this.RaisePropertyChanged("sellunit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> quoteType {
            get {
                return this.quoteTypeField;
            }
            set {
                this.quoteTypeField = value;
                this.RaisePropertyChanged("quoteType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<double> consignPrice {
            get {
                return this.consignPriceField;
            }
            set {
                this.consignPriceField = value;
                this.RaisePropertyChanged("consignPrice");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.product.api.alibaba.com")]
    public partial class ProductPriceRange : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> startQuantityField;
        
        private System.Nullable<double> priceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> startQuantity {
            get {
                return this.startQuantityField;
            }
            set {
                this.startQuantityField = value;
                this.RaisePropertyChanged("startQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<double> price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.product.api.alibaba.com")]
    public partial class SKUAttrInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> attributeIDField;
        
        private System.Nullable<long> attValueIDField;
        
        private string attributeValueField;
        
        private string customValueNameField;
        
        private string skuImageUrlField;
        
        private string attributeDisplayNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> attributeID {
            get {
                return this.attributeIDField;
            }
            set {
                this.attributeIDField = value;
                this.RaisePropertyChanged("attributeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<long> attValueID {
            get {
                return this.attValueIDField;
            }
            set {
                this.attValueIDField = value;
                this.RaisePropertyChanged("attValueID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string attributeValue {
            get {
                return this.attributeValueField;
            }
            set {
                this.attributeValueField = value;
                this.RaisePropertyChanged("attributeValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string customValueName {
            get {
                return this.customValueNameField;
            }
            set {
                this.customValueNameField = value;
                this.RaisePropertyChanged("customValueName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string skuImageUrl {
            get {
                return this.skuImageUrlField;
            }
            set {
                this.skuImageUrlField = value;
                this.RaisePropertyChanged("skuImageUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string attributeDisplayName {
            get {
                return this.attributeDisplayNameField;
            }
            set {
                this.attributeDisplayNameField = value;
                this.RaisePropertyChanged("attributeDisplayName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.product.api.alibaba.com")]
    public partial class ProductSKUInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SKUAttrInfo[] attributesField;
        
        private string cargoNumberField;
        
        private System.Nullable<int> amountOnSaleField;
        
        private System.Nullable<double> retailPriceField;
        
        private System.Nullable<double> priceField;
        
        private ProductPriceRange[] priceRangeField;
        
        private string skuCodeField;
        
        private System.Nullable<long> skuIdField;
        
        private string specIdField;
        
        private System.Nullable<double> consignPriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayElement")]
        public SKUAttrInfo[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
                this.RaisePropertyChanged("attributes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string cargoNumber {
            get {
                return this.cargoNumberField;
            }
            set {
                this.cargoNumberField = value;
                this.RaisePropertyChanged("cargoNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> amountOnSale {
            get {
                return this.amountOnSaleField;
            }
            set {
                this.amountOnSaleField = value;
                this.RaisePropertyChanged("amountOnSale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<double> retailPrice {
            get {
                return this.retailPriceField;
            }
            set {
                this.retailPriceField = value;
                this.RaisePropertyChanged("retailPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<double> price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayElement")]
        public ProductPriceRange[] priceRange {
            get {
                return this.priceRangeField;
            }
            set {
                this.priceRangeField = value;
                this.RaisePropertyChanged("priceRange");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string skuCode {
            get {
                return this.skuCodeField;
            }
            set {
                this.skuCodeField = value;
                this.RaisePropertyChanged("skuCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<long> skuId {
            get {
                return this.skuIdField;
            }
            set {
                this.skuIdField = value;
                this.RaisePropertyChanged("skuId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string specId {
            get {
                return this.specIdField;
            }
            set {
                this.specIdField = value;
                this.RaisePropertyChanged("specId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<double> consignPrice {
            get {
                return this.consignPriceField;
            }
            set {
                this.consignPriceField = value;
                this.RaisePropertyChanged("consignPrice");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.product.api.alibaba.com")]
    public partial class ProductImageInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] imagesField;
        
        private System.Nullable<bool> isWatermarkField;
        
        private System.Nullable<bool> isWatermarkFrameField;
        
        private string watermarkPositionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayElement")]
        public string[] images {
            get {
                return this.imagesField;
            }
            set {
                this.imagesField = value;
                this.RaisePropertyChanged("images");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<bool> isWatermark {
            get {
                return this.isWatermarkField;
            }
            set {
                this.isWatermarkField = value;
                this.RaisePropertyChanged("isWatermark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<bool> isWatermarkFrame {
            get {
                return this.isWatermarkFrameField;
            }
            set {
                this.isWatermarkFrameField = value;
                this.RaisePropertyChanged("isWatermarkFrame");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string watermarkPosition {
            get {
                return this.watermarkPositionField;
            }
            set {
                this.watermarkPositionField = value;
                this.RaisePropertyChanged("watermarkPosition");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.product.api.alibaba.com")]
    public partial class ProductAttribute : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> attributeIDField;
        
        private string attributeNameField;
        
        private System.Nullable<long> valueIDField;
        
        private string valueField;
        
        private System.Nullable<bool> isCustomField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> attributeID {
            get {
                return this.attributeIDField;
            }
            set {
                this.attributeIDField = value;
                this.RaisePropertyChanged("attributeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string attributeName {
            get {
                return this.attributeNameField;
            }
            set {
                this.attributeNameField = value;
                this.RaisePropertyChanged("attributeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<long> valueID {
            get {
                return this.valueIDField;
            }
            set {
                this.valueIDField = value;
                this.RaisePropertyChanged("valueID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<bool> isCustom {
            get {
                return this.isCustomField;
            }
            set {
                this.isCustomField = value;
                this.RaisePropertyChanged("isCustom");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.product.api.alibaba.com")]
    public partial class ProductInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> productIDField;
        
        private string productTypeField;
        
        private System.Nullable<long> categoryIDField;
        
        private ProductAttribute[] attributesField;
        
        private System.Nullable<long>[] groupIDField;
        
        private string statusField;
        
        private string subjectField;
        
        private string descriptionField;
        
        private string languageField;
        
        private System.Nullable<int> periodOfValidityField;
        
        private System.Nullable<int> bizTypeField;
        
        private System.Nullable<bool> pictureAuthField;
        
        private ProductImageInfo imageField;
        
        private ProductSKUInfo[] skuInfosField;
        
        private ProductSaleInfo saleInfoField;
        
        private ProductShippingInfo shippingInfoField;
        
        private ProductInternationalTradeInfo internationalTradeInfoField;
        
        private ProductExtendInfo[] extendInfosField;
        
        private System.Nullable<int> qualityLevelField;
        
        private string categoryNameField;
        
        private string mainVedioField;
        
        private string productCargoNumberField;
        
        private System.Nullable<bool> crossBorderOfferField;
        
        private System.Nullable<System.DateTime> createTimeField;
        
        private System.Nullable<System.DateTime> lastUpdateTimeField;
        
        private System.Nullable<System.DateTime> expireTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> productID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
                this.RaisePropertyChanged("productID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string productType {
            get {
                return this.productTypeField;
            }
            set {
                this.productTypeField = value;
                this.RaisePropertyChanged("productType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<long> categoryID {
            get {
                return this.categoryIDField;
            }
            set {
                this.categoryIDField = value;
                this.RaisePropertyChanged("categoryID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayElement")]
        public ProductAttribute[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
                this.RaisePropertyChanged("attributes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayElement")]
        public System.Nullable<long>[] groupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
                this.RaisePropertyChanged("groupID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> periodOfValidity {
            get {
                return this.periodOfValidityField;
            }
            set {
                this.periodOfValidityField = value;
                this.RaisePropertyChanged("periodOfValidity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<int> bizType {
            get {
                return this.bizTypeField;
            }
            set {
                this.bizTypeField = value;
                this.RaisePropertyChanged("bizType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<bool> pictureAuth {
            get {
                return this.pictureAuthField;
            }
            set {
                this.pictureAuthField = value;
                this.RaisePropertyChanged("pictureAuth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public ProductImageInfo image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
                this.RaisePropertyChanged("image");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=13)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayElement")]
        public ProductSKUInfo[] skuInfos {
            get {
                return this.skuInfosField;
            }
            set {
                this.skuInfosField = value;
                this.RaisePropertyChanged("skuInfos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public ProductSaleInfo saleInfo {
            get {
                return this.saleInfoField;
            }
            set {
                this.saleInfoField = value;
                this.RaisePropertyChanged("saleInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public ProductShippingInfo shippingInfo {
            get {
                return this.shippingInfoField;
            }
            set {
                this.shippingInfoField = value;
                this.RaisePropertyChanged("shippingInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public ProductInternationalTradeInfo internationalTradeInfo {
            get {
                return this.internationalTradeInfoField;
            }
            set {
                this.internationalTradeInfoField = value;
                this.RaisePropertyChanged("internationalTradeInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=17)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayElement")]
        public ProductExtendInfo[] extendInfos {
            get {
                return this.extendInfosField;
            }
            set {
                this.extendInfosField = value;
                this.RaisePropertyChanged("extendInfos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<int> qualityLevel {
            get {
                return this.qualityLevelField;
            }
            set {
                this.qualityLevelField = value;
                this.RaisePropertyChanged("qualityLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string categoryName {
            get {
                return this.categoryNameField;
            }
            set {
                this.categoryNameField = value;
                this.RaisePropertyChanged("categoryName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string mainVedio {
            get {
                return this.mainVedioField;
            }
            set {
                this.mainVedioField = value;
                this.RaisePropertyChanged("mainVedio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public string productCargoNumber {
            get {
                return this.productCargoNumberField;
            }
            set {
                this.productCargoNumberField = value;
                this.RaisePropertyChanged("productCargoNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public System.Nullable<bool> crossBorderOffer {
            get {
                return this.crossBorderOfferField;
            }
            set {
                this.crossBorderOfferField = value;
                this.RaisePropertyChanged("crossBorderOffer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public System.Nullable<System.DateTime> createTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
                this.RaisePropertyChanged("createTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public System.Nullable<System.DateTime> lastUpdateTime {
            get {
                return this.lastUpdateTimeField;
            }
            set {
                this.lastUpdateTimeField = value;
                this.RaisePropertyChanged("lastUpdateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<System.DateTime> expireTime {
            get {
                return this.expireTimeField;
            }
            set {
                this.expireTimeField = value;
                this.RaisePropertyChanged("expireTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.product.api.alibaba.com")]
    public partial class AlibabaProductGetResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ProductInfo productInfoField;
        
        private ProductBizGroupInfo[] bizGroupInfosField;
        
        private System.Nullable<System.DateTime> createTimeField;
        
        private System.Nullable<System.DateTime> lastUpdateTimeField;
        
        private System.Nullable<System.DateTime> lastRepostTimeField;
        
        private System.Nullable<System.DateTime> approvedTimeField;
        
        private System.Nullable<System.DateTime> expireTimeField;
        
        private string errMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public ProductInfo productInfo {
            get {
                return this.productInfoField;
            }
            set {
                this.productInfoField = value;
                this.RaisePropertyChanged("productInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayElement")]
        public ProductBizGroupInfo[] bizGroupInfos {
            get {
                return this.bizGroupInfosField;
            }
            set {
                this.bizGroupInfosField = value;
                this.RaisePropertyChanged("bizGroupInfos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> createTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
                this.RaisePropertyChanged("createTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> lastUpdateTime {
            get {
                return this.lastUpdateTimeField;
            }
            set {
                this.lastUpdateTimeField = value;
                this.RaisePropertyChanged("lastUpdateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> lastRepostTime {
            get {
                return this.lastRepostTimeField;
            }
            set {
                this.lastRepostTimeField = value;
                this.RaisePropertyChanged("lastRepostTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> approvedTime {
            get {
                return this.approvedTimeField;
            }
            set {
                this.approvedTimeField = value;
                this.RaisePropertyChanged("approvedTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> expireTime {
            get {
                return this.expireTimeField;
            }
            set {
                this.expireTimeField = value;
                this.RaisePropertyChanged("expireTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string errMsg {
            get {
                return this.errMsgField;
            }
            set {
                this.errMsgField = value;
                this.RaisePropertyChanged("errMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.product.api.alibaba.com")]
    public partial class AlibabaProductGetResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestIdField;
        
        private string bizIdField;
        
        private AlibabaProductGetResult resultField;
        
        private ApiInvocationProperty[] propertiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("requestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string bizId {
            get {
                return this.bizIdField;
            }
            set {
                this.bizIdField = value;
                this.RaisePropertyChanged("bizId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public AlibabaProductGetResult result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayElement", Namespace="http://common.api.alibaba.com")]
        public ApiInvocationProperty[] properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
                this.RaisePropertyChanged("properties");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://common.api.alibaba.com")]
    public partial class ApiInvocationProperty : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.product.api.alibaba.com")]
    public partial class AlibabaProductGetParams : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> productIDField;
        
        private string webSiteField;
        
        private string sceneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> productID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
                this.RaisePropertyChanged("productID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string webSite {
            get {
                return this.webSiteField;
            }
            set {
                this.webSiteField = value;
                this.RaisePropertyChanged("webSite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string scene {
            get {
                return this.sceneField;
            }
            set {
                this.sceneField = value;
                this.RaisePropertyChanged("scene");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.product.api.alibaba.com")]
    public partial class AlibabaProductGetRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accessTokenField;
        
        private System.Nullable<long> aopTimestampField;
        
        private AlibabaProductGetParams paramsField;
        
        private ApiInvocationProperty[] propertiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string accessToken {
            get {
                return this.accessTokenField;
            }
            set {
                this.accessTokenField = value;
                this.RaisePropertyChanged("accessToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<long> aopTimestamp {
            get {
                return this.aopTimestampField;
            }
            set {
                this.aopTimestampField = value;
                this.RaisePropertyChanged("aopTimestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public AlibabaProductGetParams @params {
            get {
                return this.paramsField;
            }
            set {
                this.paramsField = value;
                this.RaisePropertyChanged("params");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("arrayElement", Namespace="http://common.api.alibaba.com")]
        public ApiInvocationProperty[] properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
                this.RaisePropertyChanged("properties");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://alibaba-product-get.product.api.alibaba.com", ConfigurationName="ServiceReference1.AlibabaProductGetPort")]
    public interface AlibabaProductGetPort {
        
        // CODEGEN: 操作 invoke 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(K3CloudCs.ServiceReference1.ApiExceptionInfo), Action="", Name="ApiExceptionInfo", Namespace="http://common.api.alibaba.com")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        K3CloudCs.ServiceReference1.invokeResponse1 invoke(K3CloudCs.ServiceReference1.invoke1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<K3CloudCs.ServiceReference1.invokeResponse1> invokeAsync(K3CloudCs.ServiceReference1.invoke1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://alibaba-product-get.product.api.alibaba.com")]
    public partial class invoke : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AlibabaProductGetRequest argField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public AlibabaProductGetRequest arg {
            get {
                return this.argField;
            }
            set {
                this.argField = value;
                this.RaisePropertyChanged("arg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://alibaba-product-get.product.api.alibaba.com")]
    public partial class invokeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AlibabaProductGetResponse resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public AlibabaProductGetResponse result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invoke1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alibaba-product-get.product.api.alibaba.com", Order=0)]
        public K3CloudCs.ServiceReference1.invoke invoke;
        
        public invoke1() {
        }
        
        public invoke1(K3CloudCs.ServiceReference1.invoke invoke) {
            this.invoke = invoke;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alibaba-product-get.product.api.alibaba.com", Order=0)]
        public K3CloudCs.ServiceReference1.invokeResponse invokeResponse;
        
        public invokeResponse1() {
        }
        
        public invokeResponse1(K3CloudCs.ServiceReference1.invokeResponse invokeResponse) {
            this.invokeResponse = invokeResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AlibabaProductGetPortChannel : K3CloudCs.ServiceReference1.AlibabaProductGetPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlibabaProductGetPortClient : System.ServiceModel.ClientBase<K3CloudCs.ServiceReference1.AlibabaProductGetPort>, K3CloudCs.ServiceReference1.AlibabaProductGetPort {
        
        public AlibabaProductGetPortClient() {
        }
        
        public AlibabaProductGetPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlibabaProductGetPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlibabaProductGetPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlibabaProductGetPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        K3CloudCs.ServiceReference1.invokeResponse1 K3CloudCs.ServiceReference1.AlibabaProductGetPort.invoke(K3CloudCs.ServiceReference1.invoke1 request) {
            return base.Channel.invoke(request);
        }
        
        public K3CloudCs.ServiceReference1.invokeResponse invoke(K3CloudCs.ServiceReference1.invoke invoke1) {
            K3CloudCs.ServiceReference1.invoke1 inValue = new K3CloudCs.ServiceReference1.invoke1();
            inValue.invoke = invoke1;
            K3CloudCs.ServiceReference1.invokeResponse1 retVal = ((K3CloudCs.ServiceReference1.AlibabaProductGetPort)(this)).invoke(inValue);
            return retVal.invokeResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<K3CloudCs.ServiceReference1.invokeResponse1> K3CloudCs.ServiceReference1.AlibabaProductGetPort.invokeAsync(K3CloudCs.ServiceReference1.invoke1 request) {
            return base.Channel.invokeAsync(request);
        }
        
        public System.Threading.Tasks.Task<K3CloudCs.ServiceReference1.invokeResponse1> invokeAsync(K3CloudCs.ServiceReference1.invoke invoke) {
            K3CloudCs.ServiceReference1.invoke1 inValue = new K3CloudCs.ServiceReference1.invoke1();
            inValue.invoke = invoke;
            return ((K3CloudCs.ServiceReference1.AlibabaProductGetPort)(this)).invokeAsync(inValue);
        }
    }
}
